name: Sync Fork with Upstream

on:
  schedule:
    # Runs every day at midnight UTC (you can adjust the schedule)
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows you to trigger manually.

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Add Upstream
        run: |
          git remote add upstream https://github.com/original-owner/original-repo.git
          git fetch upstream
      
      - name: Sync with Upstream
        run: |
          git checkout main
          git merge upstream/main --no-edit
      
      - name: Push Changes to Fork
        run: |
          git push origin main
